In [2]:
import pandas as pd

In [ ]:
data_dons = pd.read_csv("https://storage.data.gov.my/healthcare/blood_donations.csv")
data_dons.head()

         date blood_type  donations
0  2006-01-01        all        525
1  2006-01-02        all        227
2  2006-01-03        all        112
3  2006-01-04        all        391
4  2006-01-05        all        582

In [4]:
data_dons.rename({
    "blood_type" : "groupe_sanguins",
    "donations"  : "dons"
},inplace= True , axis= 1)

data_dons.head()

         date groupe_sanguins  dons
0  2006-01-01             all   525
1  2006-01-02             all   227
2  2006-01-03             all   112
3  2006-01-04             all   391
4  2006-01-05             all   582

In [8]:
data_dons.shape

(37795, 3)

In [7]:
data_dons.info()

<class 'pandas.DataFrame'>
RangeIndex: 37795 entries, 0 to 37794
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             37795 non-null  str
 1   groupe_sanguins  37795 non-null  str
 2   dons             37795 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.3 MB

In [5]:
data_dons.to_csv("data_dons.csv", index = False)